Repository ricardo-andre-pool-cen/Equipo-0_prototipo_de_software_-seudo_repositorio, pull requests merged in 2024-09, with the labels that each got.

#53 Actualizacion de contenidos: perfección de la calidad
  Act#1 Descripción del proyecto.md
  Act#2 Administración.md
  Act#3 Requisitos Funcionales
  Act#3 Requisitos Funcionales.md
  Act#4 Requisitos No funcionales.md
  Act#4 Requisitos no funcionales
  Act#5 Presentación
  Act#5 Presentación.md
  Act#6_Competencias.md
  Comparación entre licenciaturas, UADY y TECNM
  Comparación entre licenciaturas, UADY y TECNM.md
  README.md
Labels: documentation, enhancement

#56 Finalizada la Act#1_Descripcion del proyecto, Actualizada la rubrica
  Act#1 Descripción del proyecto.md
  Act#2 Administración.md
  Act#3 Requisitos Funcionales.md
  Act#6 Competencias.md
Labels: documentation

#57 Contribución competencias genéricas y específicas.
  Competencias Genéricas y específicas.
Labels: enhancement
