Repository ricardo-andre-pool-cen/Equipo-0_prototipo_de_software_-seudo_repositorio, pull requests merged in 2024-10, with the labels that each got.

#64 Finalización de la Act#6_Competencias
  Act#1 Descripción del proyecto.md
  Act#2 Administración.md
  Act#3 Requisitos Funcionales.md
  Act#4 Requisitos No funcionales.md
  Act#5 Presentación.md
  Act#6 Competencias.md
  Comparación entre licenciaturas, UADY y TECNM.md
  Materiales/Captura de pantalla 2024-09-30 170523.png
  Materiales/Captura de pantalla 2024-09-30 171238.png
  Materiales/Captura de pantalla 2024-09-30 171443.png
  README.md
Labels: documentation, enhancement

#78 Actualización de rama
  Act#1 Descripción del proyecto.
  Act#2 Administración
  Act#3 Requisitos Funcionales
  Act#4 Requisitos no funcionales
  Act#5 Presentación
  Comparación entre licenciaturas, UADY y TECNM
  Competencias Genéricas y específicas.
  ENGLISH/english_test
  ESPAÑOL/Act#1 Descripción del proyecto.md
  ESPAÑOL/Act#2 Administración.md
  ESPAÑOL/Act#3 Requisitos Funcionales.md
  ESPAÑOL/Act#4 Requisitos No funcionales.md
  ESPAÑOL/Act#5 Diseño.md
  ESPAÑOL/Act#6 Presentación.md
  ESPAÑOL/Act#7 Competencias.md
  ESPAÑOL/Periodo_1/Act#1_Descripción del proyecto.md
  ESPAÑOL/Periodo_1/Dia 14.md
  ESPAÑOL/Periodo_1/Dia 16.md
  ESPAÑOL/Periodo_1/README.md
  ESPAÑOL/Pre-periodo/09 de Octubre.
  ESPAÑOL/Pre-periodo/README.md
  Materials-Materiales/Captura de pantalla 2024-09-30 170523.png
  Materials-Materiales/Captura de pantalla 2024-09-30 171238.png
  Materials-Materiales/Captura de pantalla 2024-09-30 171443.png
  README.md
Labels: documentation

#79 Importación del nuevo contenido y la organización hacia el cuerpo del proyecto
  Act#1 Descripción del proyecto.md
  Act#2 Administración.md
  Act#3 Requisitos Funcionales.md
  Act#4 Requisitos No funcionales.md
  Act#5 Presentación.md
  Act#6 Competencias.md
  Comparación entre licenciaturas, UADY y TECNM.md
  ENGLISH/english_test
  ESPAÑOL/Act#1 Descripción del proyecto.md
  ESPAÑOL/Act#2 Administración.md
  ESPAÑOL/Act#3 Requisitos Funcionales.md
  ESPAÑOL/Act#4 Requisitos No funcionales.md
  ESPAÑOL/Act#5 Diseño.md
  ESPAÑOL/Act#6 Presentación.md
  ESPAÑOL/Act#7 Competencias.md
  ESPAÑOL/Periodo_1/Act#1_Descripción del proyecto.md
  ESPAÑOL/Periodo_1/Dia 14.md
  ESPAÑOL/Periodo_1/Dia 16.md
  ESPAÑOL/Periodo_1/README.md
  ESPAÑOL/Pre-periodo/09 de Octubre.
  ESPAÑOL/Pre-periodo/README.md
  Materials-Materiales/Captura de pantalla 2024-09-30 170523.png
  Materials-Materiales/Captura de pantalla 2024-09-30 171238.png
  Materials-Materiales/Captura de pantalla 2024-09-30 171443.png
  README.md
Labels: enhancement

#82 Contribución de día 17 de Octubre.
  ENGLISH/Act#1 Proyect description.md
  ENGLISH/Act#2 Managment.md
  ENGLISH/Act#3 Functional requirements.md
  ENGLISH/Act#4 Non-functional requirements.md
  ENGLISH/Act#5 Design.md
  ENGLISH/Act#6 Presentation.md
  ENGLISH/Act#7 Competences.md
  ENGLISH/Pre-sprint/Day 9.md
  ENGLISH/Pre-sprint/README.md
  ENGLISH/Sprint_1/Act#1 Proyect description.md
  ENGLISH/Sprint_1/Act#3 Functional requirements.md
  ENGLISH/Sprint_1/Act#4 Non-functional requirements.md
  ENGLISH/Sprint_1/Day 14.md
  ENGLISH/Sprint_1/Day 16.md
  ENGLISH/Sprint_1/Day 17.md
  ENGLISH/Sprint_1/README.md
  ENGLISH/english_test
  ESPANOL/Act#1 Descripción del proyecto.md
  ESPANOL/Act#2 Administración.md
  ESPANOL/Act#3 Requisitos Funcionales.md
  ESPANOL/Act#4 Requisitos No funcionales.md
  ESPANOL/Act#5 Diseño.md
  ESPANOL/Act#6 Presentación.md
  ESPANOL/Act#7 Competencias.md
  ESPANOL/Periodo_1/Act#1_Descripción del proyecto.md
  ESPANOL/Periodo_1/Act#3 Requisitos Funcionales.md
  ESPANOL/Periodo_1/Act#4 Requisitos No funcionales.md
  ESPANOL/Periodo_1/Día 14.md
  ESPANOL/Periodo_1/Día 16.md
  ESPANOL/Periodo_1/Día 17.md
  ESPANOL/Periodo_1/README.md
  ESPANOL/Pre-periodo/Día 9.md
  ESPANOL/Pre-periodo/README.md
  ESPAÑOL/Periodo_1/README.md
  ESPAÑOL/Pre-periodo/09 de Octubre.
Labels: documentation, enhancement

#93 Importe de los contenidos nuevos de mi rama hacia el cuerpo del proyecto.
  ESPANOL/Periodo_1/Informe de investigación - El nuevo proceso.md
  README.md
Labels: documentation

#94 reparacion de daños
  ENGLISH/Act#1 Proyect description.md
  ENGLISH/Act#2 Managment.md
  ENGLISH/Act#3 Functional requirements.md
  ENGLISH/Act#4 Non-functional requirements.md
  ENGLISH/Act#5 Design.md
  ENGLISH/Act#6 Presentation.md
  ENGLISH/Act#7 Competences.md
  ENGLISH/Pre-sprint/Day 9.md
  ENGLISH/Pre-sprint/README.md
  ENGLISH/Sprint_1/Act#1 Proyect description.md
  ENGLISH/Sprint_1/Act#3 Functional requirements.md
  ENGLISH/Sprint_1/Act#4 Non-functional requirements.md
  ENGLISH/Sprint_1/Day 14.md
  ENGLISH/Sprint_1/Day 16.md
  ENGLISH/Sprint_1/Day 17.md
  ENGLISH/Sprint_1/README.md
  ENGLISH/english_test
  ESPANOL/Act#1 Descripción del proyecto.md
  ESPANOL/Act#2 Administración.md
  ESPANOL/Act#3 Requisitos Funcionales.md
  ESPANOL/Act#4 Requisitos No funcionales.md
  ESPANOL/Act#5 Diseño.md
  ESPANOL/Act#6 Presentación.md
  ESPANOL/Act#7 Competencias.md
  ESPANOL/Periodo_1/Act#1_Descripción del proyecto.md
  ESPANOL/Periodo_1/Act#3 Requisitos Funcionales.md
  ESPANOL/Periodo_1/Act#4 Requisitos No funcionales.md
  ESPANOL/Periodo_1/Día 14.md
  ESPANOL/Periodo_1/Día 16.md
  ESPANOL/Periodo_1/Día 17.md
  ESPANOL/Periodo_1/Informe de investigación - El nuevo proceso.md
  ESPANOL/Periodo_1/README.md
  ESPANOL/Pre-periodo/Día 9.md
  ESPANOL/Pre-periodo/README.md
  README.md
Labels: documentation

#98 Historias de usuario
  ESPANOL/Periodo_1/Informe de investigación - El nuevo proceso.md
  Guión para la presentación del proyecto.
  Materials-Materiales/Captura de pantalla 2024-09-30 170523.png
  Materials-Materiales/Captura de pantalla 2024-09-30 171238.png
  Materials-Materiales/Captura de pantalla 2024-09-30 171443.png
Labels: documentation, enhancement

#97 Historias de Usuario.
  ENGLISH/Act#3 Functional requirements.md
  ENGLISH/Pre-sprint/Day 16.md
  ENGLISH/Pre-sprint/Day 18.md
  ESPANOL/Act#3 Requisitos Funcionales.md
  ESPANOL/Periodo_1/Día 16.md
  ESPANOL/Periodo_1/Día 18.md
Labels: documentation, enhancement

#104 Guión y actualización de Historias de Usuario.
  ENGLISH/Act#3 Functional requirements.md
  ENGLISH/Act#6 Presentation.md
  ENGLISH/Pre-sprint/Day 24.md
  ESPANOL/Act#3 Requisitos Funcionales.md
  ESPANOL/Act#6 Presentación.md
  ESPANOL/Periodo_1/Día 24.md
Labels: documentation, enhancement

#106 Perla canche
  ESPANOL/Act#5 Diseño.md
Labels: enhancement

#107 Herramienta de diseño ada#5
  ESPANOL/Act#5 Diseño.md
Labels: enhancement

#112 Importación de la reforma de contenidos.
  Act#1 Introduction.md
  Act#2 Managment.md
  Act#3 Functional requirements.md
  Act#4 Non-functional requirements.md
  Act#5 Design.md
  Act#6 Presentation.md
  Act#7 Competences.md
  Materials/Captura de pantalla 2024-09-30 171238.png
  Materials/Captura de pantalla 2024-09-30 171443.png
  Materials/Captura de pantalla 2024-10-19 083602.png
  Materials/Captura de pantalla 2024-10-28 113147.png
  Pre-sprint/Day 9.md
  Pre-sprint/README.md
  README.md
  Sprint_1/Day 14.md
  Sprint_1/Day 16.md
  Sprint_1/Day 17.md
  Sprint_1/Day 18.md
  Sprint_1/Informe de investigación - El nuevo proceso.md
  Sprint_1/Problem statement.md
  Sprint_1/README.md
  Sprint_2/Day 21.md
  Sprint_2/Day 23.md
  Sprint_2/Day 24.md
  Sprint_2/Problem statement.md
  Sprint_2/README.md
  Sprint_3/Day 28.md
  Sprint_3/Problem statement.md
Labels: documentation, enhancement
